apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimilguk-boot3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimilguk-boot3
  template:
    metadata:
      labels:
        app: kimilguk-boot3
    spec:
      containers:
        - name: kimilguk-boot3
          image: kimilguk/kimilguk-boot3
          imagePullPolicy: Always
          ports:
            - name: kimilguk-boot3
              hostPort: 8080
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kimilguk-boot3
spec:
  type: NodePort
  ports:
    - name: nodejsboard
      port: 80
      nodePort: 30180
      targetPort: 8080
      protocol: TCP
  selector:
    app: kimilguk-boot3